[package]
name = "wsk-vm"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[dependencies]
log = "0.4.27"
env_logger = "0.11.8"
goblin = "0.9.3"
clap = { version = "4.5.38", features = ["derive"] }
libc = "0.2.172"

[profile.release]
debug = true
